name: My Action
description: A GitHub Action that echoes a name and executes a Python script.
inputs:
  name:
    description: 'The name to echo'
    required: true
    default: 'World'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}